### ISSUE TITLE
error Invalid character

### ISSUE THREAD

**Issue by mcanevet** [crossplane-contrib/provider-upjet-mysql#10]
I have an AWS RDS cluster with automatic rotation of master user password in SecretsManager.

In order to configure the Crossplane MySQL provider, I use an ExternalSecret to map the credentials stored in AWS SecretsManager to a Kubernetes Secret.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-poc-root-password
  namespace: crossplane-system
spec:
  data:
    - remoteRef:
        key: >-
          arn:aws:secretsmanager:us-west-2:123456789:secret:rds!cluster-11ab2d57-71c7-44f1-988b-87f9182f44b9-A7SlTr
        property: username
      secretKey: username
    - remoteRef:
        key: >-
          arn:aws:secretsmanager:us-west-2:123456789:secret:rds!cluster-11ab2d57-71c7-44f1-988b-87f9182f44b9-A7SlTr
        property: password
      secretKey: password
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: database-platform-poc-secretsmanager
  target:
    name: mysql-poc-root-password
    template:
      data:
        credentials: |
          {
            "endpoint": "mysql-poc.cluster-qwertyuiop.us-west-2.rds.amazonaws.com",
            "readerEndpoint": "mysql-poc.cluster-ro-qwertyuiop.us-west-2.rds.amazonaws.com",
            "password": "{{ .password}}",
            "port": "3306",
            "username": "{{ .username}}"
          }
      engineVersion: v2
```
Then use it in my Provider configuration:
```yaml
apiVersion: mysql.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: mysql-poc
spec:
  credentials:
    secretRef:
      key: credentials
      name: mysql-poc-root-password
      namespace: crossplane-system
    source: Secret
```

 It works fine, except sometimes the generated password contains a character that do some weird unicode conversion:
For example, when AWS generates this root password: `mDDvkb:4%{D$RS-JXl5*[P<c3M!%E`, I have this error message: `"cannot run refresh: refresh failed: Invalid character: This character is not used within the language.\nInvalid template control keyword: \"D\" is not a valid template control keyword. Did you mean \"if\"?"` and when I look into the provider logs I can see that somehow it converted the password to `mDDvkb:4%{D$RS-JXl5*[P\\u003c3M!%E` in the provider configuration block.
Unfortunately I don't think I can tell RDS to not use special characters for master user password
